modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Gaming32/bingo/issues"

[[mods]]
modId="bingo"
version="${version}"
displayName="Bingo"
logoFile="icon.png"
displayTest="IGNORE_SERVER_VERSION"

description='''
A mod for playing bingo! Works best if on both client and server, but also has compat for Vanilla clients.
'''

[[dependencies.bingo]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.bingo]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.21)"
   ordering="NONE"
   side="BOTH"

[[dependencies.bingo]]
   modId="architectury"
   mandatory=true
   versionRange="[9.1.12,)"
   ordering="NONE"
   side="BOTH"
