[versions]
emi = "1.1.16+1.21.1"
fabric-api = "0.129.0+1.21.8"
fabric-loader = "0.16.14"
jei = "19.22.0.315"
mcdev-annotations = "2.1.0"
minecraft = "1.21.8"
mixin = "0.8.5-SNAPSHOT"
mixinextras = "0.4.1"
mod-publish-plugin = "0.8.4"
modmenu = "15.0.0-beta.3"
neoforge = "9"
nightconfig = "3.8.2"
parchment-date = "2025.06.29"
parchment-mcversion = "1.21.6"
rei = "20.0.810"
unimined = "1.3.16-SNAPSHOT"

[libraries]
emi = { module = "dev.emi:emi-xplat-intermediary", version.ref = "emi" }
jei = { module = "mezz.jei:jei-1.21.1-common-api", version.ref = "jei" }
mcdev-annotations = { module = "com.demonwav.mcdev:annotations", version.ref = "mcdev-annotations" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
mixinextras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
nightconfig-core = { module = "com.electronwill.night-config:core", version.ref = "nightconfig" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }
rei = { module = "me.shedaniel:RoughlyEnoughItems-api", version.ref = "rei" }

[bundles]
nightconfig = ["nightconfig-core", "nightconfig-toml"]

[plugins]
mod-publish-plugin = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish-plugin" }
unimined = { id = "xyz.wagyourtail.unimined", version.ref = "unimined" }
