modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Gaming32/bingo/issues"

[[mods]]
modId="bingo"
version="${version}"
displayName="Bingo"
logoFile="icon.png"
displayTest="IGNORE_SERVER_VERSION"

description='''
A mod for playing bingo! Works best if on both client and server, but also has compat for Vanilla clients.
'''

[[mixins]]
config = "bingo-common.mixins.json"

[[mixins]]
config = "bingo.mixins.json"

[[dependencies.bingo]]
   modId="neoforge"
   type="required"
   versionRange="[20.4.77-beta,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.bingo]]
   modId="minecraft"
   type="required"
   versionRange="[1.20.4,1.20.5)"
   ordering="NONE"
   side="BOTH"

[[dependencies.bingo]]
   modId="architectury"
   type="required"
   versionRange="[11.0.10,)"
   ordering="NONE"
   side="BOTH"
