modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Gaming32/bingo/issues"

[[mods]]
modId="bingo"
version="${version}"
displayName="Bingo"
logoFile="icon.png"

description='''
A mod for playing bingo! Works best if on both client and server, but also has compat for Vanilla clients.
'''

[[mixins]]
config = "bingo-common.mixins.json"

[[mixins]]
config = "bingo.mixins.json"

[[dependencies.bingo]]
   modId="neoforge"
   type="required"
   versionRange="[20.5.0-beta,20.6)"
   ordering="NONE"
   side="BOTH"

[[dependencies.bingo]]
   modId="minecraft"
   type="required"
   versionRange="[1.20.5,1.20.6)"
   ordering="NONE"
   side="BOTH"
