name: Gradle build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Gradle stuff
        uses: actions/cache@v4
        with:
          key: gradle-${{ hashFiles('*.gradle.kts', 'gradle.properties', '*/*.gradle.kts', 'gradle/**') }}
          restore-keys: gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/loom-cache
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Upload Fabric artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fabric-jars
          path: fabric/build/libs
      - name: Upload NeoForge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neoforge-jars
          path: neoforge/build/libs
