name: Gradle build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Cache Gradle stuff
        uses: actions/cache@v4
        with:
          key: gradle-${{ hashFiles('*.gradle.kts', 'gradle.properties', '*/*.gradle.kts', 'gradle/**') }}
          restore-keys: gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/unimined
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: zulu
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: build/libs
      - name: Run datagen
        run: ./gradlew fabricRunDatagenClient
      - name: Verify datagen up-to-date
        run: git diff --color=always --exit-code
